import 'package:suprapp/app/core/constants/app_images.dart';

class FoodModel {
  final String image;
  final String title;
  final String time;
  final String rating;
  final String location;
  final String distance;
  final String discount;
  final String numofrating;
  final String price;
  final String deliveryfee;
  final List<String> tbartext;

  FoodModel(
      {required this.image,
      required this.title,
      required this.rating,
      required this.time,
      required this.location,
      required this.distance,
      required this.discount,
      required this.numofrating,
      required this.price,
      required this.deliveryfee,
      required this.tbartext});
}

List<FoodModel> myfood = [
  FoodModel(
    image: AppImages.award,
    title: "Barbar",
    rating: "4.3",
    time: "55-65 mins",
    location: "Labanese Shawarma",
    distance: "3.1 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "999+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Businesses Lunch",
      "Healthy Meals",
      "Gathering Box",
      "Break Fast",
    ],
  ),
  FoodModel(
    image: AppImages.award,
    title: "Sushi",
    rating: "4.7",
    time: "55-65 mins",
    location: "Labanese Asian, sushi",
    distance: "3.3 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "509+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Sushi Cago Signature",
      "Authentic Boxes",
      "Miami Boxes",
      "Salmon Boxes",
    ],
  ),
  FoodModel(
    image: AppImages.award,
    title: "Kaak Al Manara",
    rating: "4.6",
    time: "55-65 mins",
    location: "Labanese Aribic, Manakish",
    distance: "2.6 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "700+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "New: Party Boxes Sliders",
      "New: Kid's Meal",
      "Break Fast",
      "The Bakery by Ka'ak Al Manara-Mouajanat",
    ],
  ),
  FoodModel(
    image: AppImages.award,
    title: "Crepe & Go",
    rating: "4.3",
    time: "55-65 mins",
    location: "Desert, Crepes",
    distance: "3.1 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "999+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Dubai Famous Kunafa",
      "Crepes",
      "Create your own",
      "Signature Creps",
    ],
  ),
  FoodModel(
      image: AppImages.award,
      title: "Mumbai Junction vegetarian Restaurant",
      rating: "4.3",
      time: "55-65 mins",
      location: "Indian, north indian, Rice ",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Authentic Indian Sweets ",
        "Mj Combo & Thali",
        "Mubbai Street Specialty",
        "Starter",
      ]),
  FoodModel(
      image: AppImages.award,
      title: "Firehouse Subs",
      rating: "4.3",
      time: "55-65 mins",
      location: "Snadwiches, Snacks",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Cream Exclusive Meal",
        "Combo Value Meal",
        "12 inch Meal",
        "8 inch Meal",
      ]),
  FoodModel(
      image: AppImages.award,
      title: "Maestro Pizza",
      rating: "4.3",
      time: "55-65 mins",
      location: "Italian, Pizza",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Taste of the world",
        "Chef s Selection Medium",
        "The original Small",
        "The Orignal Medium",
      ]),
  FoodModel(
      image: AppImages.award,
      title: "Right Bite",
      rating: "4.3",
      time: "55-65 mins",
      location: "Healthy, Breakfast",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "30 % Off",
        "New Burgers",
        "New Protein Packed 💪",
        "Power Bowls",
      ]),
  FoodModel(
      image: AppImages.award,
      title: "Laffah Restaurant",
      rating: "4.3",
      time: "55-65 mins",
      location: "Lebbanes,BBQ & Grill, Sharwarma",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Shawarma Sandwiches",
        "Shawarma",
        "Broasted",
        "Patato",
      ]),
  FoodModel(
      image: AppImages.award,
      title: "Mumbai Spices",
      rating: "4.3",
      time: "55-65 mins",
      location: " Indian, North Indian, Biryani",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Rice & Bryani",
        "Thali",
        "Mumbai Chinese",
        "Chaat & Pav Snacks",
      ]),
];
